//Max buffs
chrome.storage.local.set({ '1@armour': 7 });
chrome.storage.local.set({ '1@spin': 7 });
chrome.storage.local.set({ '1@speed': 7 });
chrome.storage.local.set({ '1@damage': 7 });

//Weapons
chrome.storage.local.set({ '1@w_axe': 5 });
chrome.storage.local.set({ '1@w_banana': 5 });
chrome.storage.local.set({ '1@w_battle_axe': 5 });
chrome.storage.local.set({ '1@w_broom': 5 });
chrome.storage.local.set({ '1@w_bullet': 5 });
chrome.storage.local.set({ '1@w_buttefly': 5 });
chrome.storage.local.set({ '1@w_carrotknife': 5 });
chrome.storage.local.set({ '1@w_claw': 5 });
chrome.storage.local.set({ '1@w_cool1': 5 });
chrome.storage.local.set({ '1@w_diaknife': 5 });
chrome.storage.local.set({ '1@w_eye_piercer': 5 });
chrome.storage.local.set({ '1@w_katana': 5 });
chrome.storage.local.set({ '1@w_kitchen_knife': 5 });
chrome.storage.local.set({ '1@w_lol_fist': 5 });
chrome.storage.local.set({ '1@w_long_axe': 5 });
chrome.storage.local.set({ '1@w_long_pendulum': 5 });
chrome.storage.local.set({ '1@w_longsword': 5 });
chrome.storage.local.set({ '1@w_mace': 5 });
chrome.storage.local.set({ '1@w_pendulum': 5 });
chrome.storage.local.set({ '1@w_pixel1': 5 });
chrome.storage.local.set({ '1@w_rocket': 5 });
chrome.storage.local.set({ '1@w_shield': 5 });
chrome.storage.local.set({ '1@w_short_dagger': 5 });
chrome.storage.local.set({ '1@w_slow_pendulum': 5 });
chrome.storage.local.set({ '1@w_spear1': 5 });
chrome.storage.local.set({ '1@w_spear2': 5 });
chrome.storage.local.set({ '1@w_speedsword': 5 });
chrome.storage.local.set({ '1@w_staff': 5 });
chrome.storage.local.set({ '1@w_superfast': 5 });
chrome.storage.local.set({ '1@w_tiny_fast_dagger': 5 });
chrome.storage.local.set({ '1@w_wearable': 5 });
chrome.storage.local.set({ '1@w_wolverine': 5 });
